# Azure Developer CLI Configuration
# This file configures the Azure Developer CLI (azd) for HSQ Forms API deployment

name: hsq-forms-api
metadata:
  template: hsq-forms-api@1.0.0

# Services configuration
services:
  api:
    project: ./src
    language: python
    host: containerapp

# Azure resource deployment configuration
infra:
  path: ./infra
  provider: bicep

# Pipeline configuration for GitHub Actions
pipeline:
  provider: github

# Environment variables that will be set during deployment
environment:
  # Database configuration (will be set by Bicep outputs)
  DATABASE_URL: ${AZURE_DATABASE_URL}
  
  # Azure Storage configuration
  AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
  AZURE_STORAGE_CONTAINER_NAME: form-uploads
  AZURE_STORAGE_TEMP_CONTAINER_NAME: temp-uploads
  
  # Application configuration
  ENVIRONMENT: ${AZURE_ENV_NAME}
  API_TITLE: HSQ Forms API
  API_VERSION: 1.0.0
  
  # CORS configuration (update for production)
  ALLOWED_ORIGINS: https://${AZURE_CONTAINER_APP_FQDN}
  
  # Enable Azure Storage (will be automatically set when deployed to Azure)
  FORCE_AZURE_STORAGE: true

# Hooks for deployment lifecycle
hooks:
  predeploy:
    shell: sh
    run: |
      echo "Running pre-deployment checks..."
      # Validate Docker build
      docker build -t hsq-forms-api-test -f Dockerfile .
      echo "Pre-deployment checks completed"
    continueOnError: false

  postdeploy:
    shell: sh
    run: |
      echo "Running post-deployment verification..."
      echo "Application deployed successfully to: ${AZURE_CONTAINER_APP_URL}"
      echo "Storage Account: ${AZURE_STORAGE_ACCOUNT_NAME}"
    continueOnError: true
