services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hsq_forms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_dev_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hsq-forms-network

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: hsq_forms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_dev_password_123
      DEBUG: "true"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["uvicorn", "src.forms_api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - hsq-forms-network

volumes:
  postgres_data:

networks:
  hsq-forms-network:
    external: true
