version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hsq_forms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_dev_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hsq-forms-network

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: hsq_forms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_dev_password_123
      DEBUG: "true"
      CORS_ORIGINS: "http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:3004"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["uvicorn", "src.forms_api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - hsq-forms-network

  # B2B Feedback Form Container
  b2b-feedback:
    build: ./forms/hsq-forms-container-b2b-feedback
    ports:
      - "3001:3000"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"
    depends_on:
      - api
    networks:
      - hsq-forms-network

  # B2B Returns Form Container  
  b2b-returns:
    build: ./forms/hsq-forms-container-b2b-returns
    ports:
      - "3002:3000"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"
    depends_on:
      - api
    networks:
      - hsq-forms-network

  # B2B Support Form Container
  b2b-support:
    build: ./forms/hsq-forms-container-b2b-support
    ports:
      - "3003:3000"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"
    depends_on:
      - api
    networks:
      - hsq-forms-network

  # B2C Returns Form Container
  b2c-returns:
    build: ./forms/hsq-forms-container-b2c-returns
    ports:
      - "3004:3000"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"
    depends_on:
      - api
    networks:
      - hsq-forms-network

volumes:
  postgres_data:

networks:
  hsq-forms-network:
    external: true
