version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hsq_forms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_dev_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hsq-forms-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
    image: hsqformsdevacr.azurecr.io/hsq-forms-api-dev:${VERSION:-latest}
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: hsq_forms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_dev_password_123
      DEBUG: "true"
      APP_ENVIRONMENT: development
    depends_on:
      postgres:
        condition: service_healthy
    command: ["uvicorn", "src.forms_api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - hsq-forms-network
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

volumes:
  postgres_data:

networks:
  hsq-forms-network:
    name: hsq-forms-network
    driver: bridge
