version: '3.8'

services:
  hsq-feedback-form:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - hsq-forms-network

networks:
  hsq-forms-network:
    external: true
