name: Configure ACR for GitHub Actions

on:
  workflow_dispatch:  # Allows manual triggering

env:
  AZURE_SUBSCRIPTION: c0b03b12-570f-4442-b337-c9175ad4037f

jobs:
  configure-acr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION }}
    
    - name: Configure ACR Network Rules (Development)
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "Configuring Dev ACR network rules to allow public access..."
          az acr update --name hsqformsdevacr --default-action Allow
          echo "Dev ACR network rules updated successfully."
          
    - name: Configure ACR Network Rules (Production)
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "Configuring Prod ACR network rules to allow public access..."
          az acr update --name hsqformsprodacr --default-action Allow
          echo "Prod ACR network rules updated successfully."
